package mAPI;

public class Constants {
	public static final int
		INDEX_BANK = 762,
		BANK_ITEM_ARRAY = 95,
		BANK_SCROLLBAR = 116,
		BANK_DEPOSIT_OFFSET = 34,
		BANK_DEPOSIT_ALL = 0,
		BANK_DEPOSIT_EQUIPPED = 4,
		BANK_DEPOSIT_SUMMONING = 6,
		BANK_DEPOSIT_PURSE = 2,
		BANK_CLOSE = 45,
		BANK_SWITCH_EQUIPMENT = 120,
		BANK_TAB_SELECTED = 1419,
		BANK_AMOUNT_INDEX = 752,
		BANK_AMOUNT_VISIBLE = 0,
		
		BANKTAB_VIEWALL = 0,
		BANKTAB_TAB1 = 1,
		BANKTAB_TAB2 = 2,
		BANKTAB_TAB3 = 3,
		BANKTAB_TAB4 = 4,
		BANKTAB_TAB5 = 5,
		BANKTAB_TAB6 = 6,
		BANKTAB_TAB7 = 7,
		BANKTAB_TAB8 = 8,
		
		INDEX_BANKINV = 763,
		BANKINV_ITEM_ARRAY = 0,		
		
		INDEX_DEPOSIT_BOX = 11,
		DEPOSIT_BOX_ITEM_ARRAY = 17,
		DEPOSIT_BOX_CLOSE = 15,
		DEPOSIT_BOX_DEPOSIT_OFFSET = 19;
	
	public static final int[] BANK_TABS = {65, 63, 61, 59, 57, 55, 53, 51, 49};
	
	public Constants() {
		throw new AssertionError();
	}

}
